web:
    build: .
    ports:
    links:
        - redis:redis
        - mongo:mongo
    ports:
        - "49160:3000"
redis:
    image: redis
    ports:
        - "6379:6379"
mongo:
    image: mongo
    ports:
        - “27017:27017”